config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :super_admins do
    get 'enterprises/index'
    get 'users/index'

    resources :enterprises
    resources :users
  end

  namespace :admins do
    get 'users/index'
    get 'enterprises/index'

    resources :users
    resources :enterprises
  end

  get 'dashboard/index'
  get 'providers/index'
  get 'product_categories/index'
  get 'clients/index'

  devise_for :users
  resources :providers
  resources :product_categories
  resources :clients
  root to: 'dashboard#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :inet
#  document_number        :string           not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string           not null
#  is_active              :boolean          default(FALSE)
#  is_admin               :boolean          default(FALSE)
#  is_super_admin         :boolean          default(FALSE)
#  last_name              :string           not null
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :inet
#  nickname               :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  enterprise_id          :bigint           not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_enterprise_id         (enterprise_id)
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (enterprise_id => enterprises.id)
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :enterprise
  validates :document_number, uniqueness: { scope: :enterprise_id }
  validates_presence_of %i[first_name last_name email document_number enterprise_id]

  def status_users
    return t('application.disabled') unless is_active
    return t('application.super_admin') if is_active && is_super_admin
    return t('application.admin') if is_active && is_admin
    return t('application.employee') if is_active && !is_admin && !is_super_admin
  end
end

app/controllers/admins/users_controller.rb
# frozen_string_literal: true

module Admins
  class UsersController < AdminsController
    before_action :verify_password, only: %w[update]
    before_action :set_user, only: %w[edit update destroy]

    def index   
      @q = User.where(enterprise_id: current_user.enterprise_id)
               .ransack(params[:q])
      @users = @q.result(distinct: true)
    end

    def new
      @user = User.new
    end

    def show; end

    def create
      @user = User.new(params_user)

      if @user.save
        redirect_to admins_users_path
        flash[:success] = 'Usuário cadastrado com sucesso.'
      else
        render :new
      end
    end

    def edit; end

    def update
      
      binding.pry
      
      if @user.update(params_user)
        redirect_to admins_users_path
        flash[:success] = 'Usuário atualizado com sucesso.'
      else
        render :edit
      end
    end

    def destroy
      if @user.destroy
        redirect_to admins_users_path
        flash[:success] = 'Usuário excluído com sucesso.'
      else
        render :index
      end
    end

    private

    def set_user
      if current_user.enterprise_id == User.find(params[:id]).enterprise_id
        @user = User.find(params[:id])
      else
        redirect_to root_path
        flash[:danger] = 'Você não tem permissão para editar este usuário.' 
      end
    end

    def params_user
      params.require(:user)
            .permit(:document_number, :email, :first_name, :is_active, :is_admin, :last_name, :nickname,
                    :password, :password_confirmation)
            .with_defaults(enterprise_id: current_user.enterprise_id)
    end

    def verify_password
      if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
        params[:user].extract!(:password, :password_confirmation)
      end
    end
  end
end

app/controllers/super_admins/enterprises_controller.rb
# frozen_string_literal: true

module SuperAdmins
  class EnterprisesController < SuperAdminsController
    before_action :set_enterprise, only: %w[edit update destroy]
    rescue_from ActiveRecord::InvalidForeignKey, with: :invalid_foreign_key

    def index
      @enterprises = Enterprise.all
    end

    def new
      @enterprise = Enterprise.new
    end

    def create
      @enterprise = Enterprise.new(params_enterprise)

      if @enterprise.save
        redirect_to super_admins_enterprises_path 
        flash[:success] = 'Empresa cadastrada com sucesso.'
      else
        render :new
      end
    end

    def edit; end

    def update
      if @enterprise.update(params_enterprise)
        redirect_to super_admins_enterprises_path
        flash[:success] = 'Empresa atualizada com sucesso.'
      else
        render :edit
      end
    end

    def destroy
      if @enterprise.destroy
        redirect_to super_admins_enterprises_path
        flash[:success] = 'Empresa excluída com sucesso.'
      else
        render :index
      end
    end

    private

    def set_enterprise
      @enterprise = Enterprise.find(params[:id])
    end

    def params_enterprise
      params.require(:enterprise).permit(:company_name, :description, :document_number, :email, :fantasy_name, :logo, :opening_date, :primary_color,
                                         :secondary_color, :is_active)
    end

    def invalid_foreign_key
      redirect_to super_admins_enterprises_path
      flash[:danger] = 'Não é possível excluir, pois há dados vinculados.'
    end
  end
end

app/controllers/super_admins/users_controller.rb
# frozen_string_literal: true

module SuperAdmins
  class UsersController < SuperAdminsController
    before_action :verify_password, only: %w[update]
    before_action :set_user, only: %w[edit update destroy]
    before_action :set_enterprise, only: %w[create new edit update destroy]

    def index
      @q = User.ransack(params[:q])
      @users = @q.result(distinct: true)
    end

    def new
      @user = User.new
    end

    def show; end

    def create
      @user = User.new(params_user)

      if @user.save
        redirect_to super_admins_users_path
        flash[:success] = 'Usuário cadastrado com sucesso.'
      else
        render :new
      end
    end

    def edit; end

    def update
      if @user.update(params_user)
        redirect_to super_admins_users_path
        flash[:success] = 'Usuário atualizado com sucesso.'
      else
        render :edit
      end
    end

    def destroy
      if @user.destroy
        redirect_to super_admins_users_path
        flash[:success] = 'Usuário excluído com sucesso.'
      else
        render :index
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def set_enterprise
      @enterprise = Enterprise.all
    end

    def params_user
      params.require(:user)
            .permit(:document_number, :email, :first_name, :is_active, :is_admin, :is_super_admin, :last_name,
                    :nickname, :enterprise_id, :password, :password_confirmation)
    end

    def verify_password
      if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
        params[:user].extract!(:password, :password_confirmation)
      end
    end
  end
end

app/controllers/super_admins_controller.rb
# frozen_string_literal: true

class SuperAdminsController < UsersController
  before_action :super_admin?

  private

  def super_admin?
    if !current_user.is_super_admin
      redirect_to root_path
      flash[:danger] = 'Você não tem permissão para acessar esta página'
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/users_helper.rb
module UsersHelper
  def enterprises_collection
    Enterprise.pluck(:company_name, :id)
              .compact
              .sort
  end
end

app/views/super_admins/users/edit.html.erb
<div class="text-center">
  <h4><%= t('.editing') %>: <%= @user.first_name %> <%= @user.last_name %></h4>
</div>
<div class="container h-100">
  <%= render partial: 'super_admins/users/components/errors.html.erb' %>
  <div class="d-flex justify-content-center h-100">
    <div class="user-card-form">
      <%= form_with(model: [:super_admins, @user], local: true) do |form| %>
        <%= render partial: 'super_admins/users/components/form.html.erb',
            locals: { form: form } %>
        <div class="row btn-actions">
          <div class="col-lg-6 mt-3">
            <%= link_to t('.cancel'), super_admins_users_path, class: 'btn btn-danger btn-user btn-block' %>
          </div>
          <div class="col-lg-6 mt-3">
            <button class="btn btn-primary btn-user btn-block">
              <%= t('.edit') %>
            </button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/super_admins/users/index.html.erb
<div class="text-center">
  <h4><%= t('.registered_users') %></h4>
</div>
<%= render partial: 'layouts/filter', locals: { url: super_admins_users_path } %>
<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <div class="row">
        <div class="col-sm-12">
          <table id="table" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th><%= t('.name')%></th>
                <th><%= t('.nickname')%></th>
                <th><%= t('.document_number')%></th>
                <th><%= t('.email')%></th>
                <th><%= t('.function')%></th>
                <th><%= t('.enterprise')%></th>
                <th class="no-sort table-buttons">
                  <%= link_to new_super_admins_user_path(@user), class: 'btn btn-success btn-circle' do %>
                    <i class="fas fa-plus"></i>
                  <% end %>
                </th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= user.first_name %> <%= user.last_name %></td>
                  <td><%= user.nickname %></td>
                  <td><%= format_document_number(user.document_number) %></td>
                  <td><%= user.email %></td>
                  <td class="text-center">
                    <span class="badge badge-<%= function_color(user.is_active, user.is_admin, user.is_super_admin) %>" style="width: 100%">
                      <%= function_translate(user.is_active, user.is_admin, user.is_super_admin) %>
                    </span>
                  </td>
                  <td><%= user.enterprise.company_name %></td>
                  <td class="table-buttons">
                    <%= link_to edit_super_admins_user_path(user), class: 'btn btn-info btn-circle' do %>
                      <i class="fas fa-edit"></i>
                    <% end %>
                    <%= link_to super_admins_user_path(user),
                        method: :delete,
                        class: 'btn btn-danger btn-circle',
                        data: { confirm: "#{t('.delete_confirm')}: #{user.first_name} #{user.last_name}?" } do %>
                      <i class="fas fa-trash"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
    $('#table').DataTable({
      "columnDefs": [{
        "targets": 'no-sort',
        "orderable": false,
      }],
      "language": {
        "url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/Portuguese-Brasil.json"
      }
    });
  });
</script>

app/views/super_admins/users/new.html.erb
<div class="text-center">
  <h4><%= t('.new_user') %></h4>
</div>
<div class="container h-100">
  <%= render partial: 'super_admins/users/components/errors.html.erb' %>
  <div class="d-flex justify-content-center h-100">
    <div class="user-card-form">
      <%= form_with(model: [:super_admins, @user], local: true) do |form| %>
        <%= render partial: 'super_admins/users/components/form.html.erb',
                   locals: { form: form } %>
        <div class="row btn-actions">
          <div class="col-lg-6 mt-3">
            <%= link_to t('.cancel'), super_admins_users_path, class: 'btn btn-danger btn-user btn-block' %>
          </div>
          <div class="col-lg-6 mt-3">
            <button class="btn btn-primary btn-user btn-block">
              <%= t('.create_new') %>
            </button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>