config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :super_admins do
    get 'enterprises/index'
    get 'users/index'

    resources :enterprises
    resources :users
  end

  namespace :admins do
    get 'users/index'
    get 'enterprises/index'

    resources :users
    resources :enterprises
  end

  get 'dashboard/index'
  get 'providers/index'
  get 'product_categories/index'
  get 'clients/index'

  devise_for :users
  resources :providers
  resources :product_categories
  resources :clients
  root to: 'dashboard#index'
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id               :bigint           not null, primary key
#  document_number  :string           not null
#  email            :string
#  first_name       :string           not null
#  last_name        :string           not null
#  nickname         :string
#  phone_number     :string
#  telephone_number :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  enterprise_id    :bigint           not null
#
# Indexes
#
#  index_clients_on_enterprise_id  (enterprise_id)
#
# Foreign Keys
#
#  fk_rails_...  (enterprise_id => enterprises.id)
#
class Client < ApplicationRecord
  belongs_to :enterprise
end

app/controllers/clients_controller.rb
# frozen_string_literal: true

class ClientsController < UsersController
  before_action :set_client, only: %w[edit update destroy]

  def index
    @q = Client.where(enterprise_id: current_user.enterprise_id)
               .ransack(params[:q])
    @clients = @q.result(distinct: true)
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(params_client)

    if @client.save
      redirect_to(clients_path)
      flash[:success] = 'Cliente cadastrado com sucesso.'
    else
      render :new
    end
  end

  def edit;
  end

  def update;
  end

  def destroy
    if @client.destroy
      redirect_to(clients_path)
      flash[:success] = 'Cliente excluído com sucesso.'
    else
      render :index
    end
  end

  private

  def set_client
    if current_user.enterprise_id == Client.find(params[:id]).enterprise_id
      @client = Client.find(params[:id])
    else
      redirect_to(root_path)
      flash[:danger] = 'Você não tem permissão para manipular este cliente.'
    end
  end

  def params_client
    params.require(:client)
          .permit(:first_name, :last_name, :nickname, :document_number, :email, :phone_number,
                  :telephone_number, :enterprise_id)
          .with_defaults(enterprise_id: current_user.enterprise_id)
  end
end

app/views/clients/index.html.erb
<div class="text-center">
  <h4><%= t('.registered_clients') %></h4>
</div>
<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <div class="row">
        <div class="col-sm-12">
          <table id="table" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th><%= t('.first_name')%></th>
                <th><%= t('.last_name')%></th>
                <th><%= t('.nickname')%></th>
                <th><%= t('.document_number')%></th>
                <th><%= t('.email')%></th>
                <th><%= t('.telephone_number')%></th>
                <th class="no-sort table-buttons">
                  <%= link_to new_client_path(@client), class: 'btn btn-success btn-circle' do %>
                    <i class="fas fa-plus"></i>
                  <% end %>
                </th>
              </tr>
            </thead>
            <tbody>
              <% @clients.each do |client| %>
                <tr>
                  <td><%= client.first_name %></td>
                  <td><%= client.last_name %></td>
                  <td><%= client.nickname %></td>
                  <td><%= format_document_number(client.document_number) %></td>
                  <td><%= client.email %></td>
                  <td><%= client.telephone_number %></td>
                  <td class="table-buttons">
                    <%= link_to edit_client_path(client), class: 'btn btn-info btn-circle' do %>
                      <i class="fas fa-edit"></i>
                    <% end %>
                    <%= link_to client_path(client),
                        method: :delete,
                        class: 'btn btn-danger btn-circle',
                        data: { confirm: "#{t('.delete_confirm')}: #{client.first_name} #{client.last_name}?" } do %>
                      <i class="fas fa-trash"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
    $('#table').DataTable({
      "columnDefs": [{
        "targets": 'no-sort',
        "orderable": false,
      }],
      "language": {
        "url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/Portuguese-Brasil.json"
      }
    });
  });
</script>

app/views/clients/new.html.erb
<div class="text-center">
  <h4><%= t('.new_client') %></h4>
</div>
<div class="container h-100">
  <%= render partial: 'clients/components/errors.html.erb' %>
  <div class="d-flex justify-content-center h-100">
    <div class="user-card-form">
      <%= form_with(model: @client, local: true) do |form| %>
        <%= render partial: 'clients/components/form.html.erb',
                   locals: { form: form } %>
        <div class="row btn-actions">
          <div class="col-lg-6 mt-3">
            <%= link_to t('.cancel'), clients_path, class: 'btn btn-danger btn-user btn-block' %>
          </div>
          <div class="col-lg-6 mt-3">
            <button class="btn btn-primary btn-user btn-block">
              <%= t('.create_new') %>
            </button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>